baseURL = "https://aws13.cloudlab.cat/"
languageCode = "es-es"
title = "cloudlab.cat â€” Repte 13"
theme = "blowfish"

enableRobotsTXT = true

[pagination]
  pagerSize = 10


[params]
  colorScheme = "ocean"
  defaultAppearance = "dark"
  autoSwitchAppearance = true
  enableSearch = true
  showReadingTime = true